source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'HTWDresden' do
	
    pod 'Alamofire'
    pod 'ObjectMapper'
    pod 'SwiftString'
    pod 'Kingfisher', '~> 2.2'
    pod 'Cartography'
    pod 'ReactiveUI'
    
end

target 'HTWDresdenTests' do
	
end
