source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'HTWDresden' do
	
	pod 'Core', :path => '../'
	pod 'Grades', :path => '../'
	pod 'Lesson', :path => '../'
	pod 'Mensa', :path => '../'
	
end

target 'HTWDresdenTests' do
	
end

