source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Core_Example', :exclusive => true do
  pod "Core", :path => "../../"
end

target 'Core_Tests', :exclusive => true do
  pod "Core", :path => "../../"

  
end
